[features]
seeds = false
skip-lint = false
[programs.devnet]
tenant_info = "HibQzdWgu2JhVVHuizrYNfyvgwk7BHjaR1ZaS6ah4eYT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jsunnykhan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
